export class ModbusVariableMapper {
  public keys: { [key: string]: number } = {
    lowproducttime: 0,
    robaguptime: 0,
    interlocktime: 0,
    runtime: 0,
    pausedtime: 0,
    faulttime: 0,
    outoffilmtime: 0,
    fullbags: 0,
    targetweight: 0,
    baglength: 0,
    bagsperminute: 0,
    topconehigh: 0,
    topconelow: 0,
    shiftefficiency: 0,
    highlimitweight: 0,
    sealtime: 0,
    striplength: 0,
    falltime: 0,
    nominalweight: 0,
    tne: 0,
    fbdelay2: 0,
    lvfdelay: 0,
    wbdelay: 0,
    wbopentime: 0,
    fbopentime: 0,
    staggerdelay: 0,
    lowlowlimit: 0,
    biasweight: 0,
    striptime: 0,
  };
}
